### ISSUE TITLE
Using large values in configurationOverrides causes conversion to scientific notation and crashes broker on startup

### ISSUE THREAD

**Issue by llevar** [confluentinc/cp-helm-charts#235]
Install kafka chart with overridden values

```
  configurationOverrides:
    "socket.request.max.bytes": 2004857600
    "message.max.bytes": 1000000012
    "replica.fetch.max.bytes": 1000000015
```

Kafka broker pods crash with errors in log:

```
echo "===> Launching ... "
+ echo '===> Launching ... '
exec /etc/confluent/docker/launch
+ exec /etc/confluent/docker/launch
===> Launching ... 
===> Launching kafka ... 
[2019-01-29 13:28:55,984] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2019-01-29 13:28:56,281] ERROR Fatal error during SupportedServerStartable startup. Prepare to shutdown (io.confluent.support.metrics.SupportedKafka)
org.apache.kafka.common.config.ConfigException: Invalid value 1.000000012e+09 for configuration message.max.bytes: Not a number of type INT
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:722)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:469)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:462)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1029)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1032)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1012)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1009)
	at kafka.server.KafkaConfig.fromProps(KafkaConfig.scala)
	at io.confluent.support.metrics.SupportedServerStartable.<init>(SupportedServerStartable.java:52)
	at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:45)
```

Config values for pod end up being:

```
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "kafka-cp-kafka-1",
    "generateName": "kafka-cp-kafka-",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/pods/kafka-cp-kafka-1",
    "uid": "bfda1956-23c9-11e9-a615-fa163e9a84ea",
    "resourceVersion": "325036",
    "creationTimestamp": "2019-01-29T13:28:22Z",
    "labels": {
      "app": "cp-kafka",
      "controller-revision-hash": "kafka-cp-kafka-745fc9956d",
      "release": "kafka",
      "statefulset.kubernetes.io/pod-name": "kafka-cp-kafka-1"
    },
    "annotations": {
      "prometheus.io/port": "5556",
      "prometheus.io/scrape": "true"
    },
    "ownerReferences": [
      {
        "apiVersion": "apps/v1",
        "kind": "StatefulSet",
        "name": "kafka-cp-kafka",
        "uid": "54280c00-23b1-11e9-a615-fa163e9a84ea",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ]
  },
  "spec": {
    "volumes": [
      {
        "name": "datadir-0",
        "persistentVolumeClaim": {
          "claimName": "datadir-0-kafka-cp-kafka-1"
        }
      },
      {
        "name": "jmx-config",
        "configMap": {
          "name": "kafka-cp-kafka-jmx-configmap",
          "defaultMode": 420
        }
      },
      {
        "name": "default-token-gwvxx",
        "secret": {
          "secretName": "default-token-gwvxx",
          "defaultMode": 420
        }
      }
    ],
    "containers": [
      {
        "name": "prometheus-jmx-exporter",
        "image": "solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143",
        "command": [
          "java",
          "-XX:+UnlockExperimentalVMOptions",
          "-XX:+UseCGroupMemoryLimitForHeap",
          "-XX:MaxRAMFraction=1",
          "-XshowSettings:vm",
          "-jar",
          "jmx_prometheus_httpserver.jar",
          "5556",
          "/etc/jmx-kafka/jmx-kafka-prometheus.yml"
        ],
        "ports": [
          {
            "containerPort": 5556,
            "protocol": "TCP"
          }
        ],
        "resources": {},
        "volumeMounts": [
          {
            "name": "jmx-config",
            "mountPath": "/etc/jmx-kafka"
          },
          {
            "name": "default-token-gwvxx",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent"
      },
      {
        "name": "cp-kafka-broker",
        "image": "confluentinc/cp-kafka:5.0.1",
        "command": [
          "sh",
          "-exc",
          "export KAFKA_BROKER_ID=${HOSTNAME##*-} && \\\nexport KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092,EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID})) && \\\nexec /etc/confluent/docker/run\n"
        ],
        "ports": [
          {
            "name": "kafka",
            "containerPort": 9092,
            "protocol": "TCP"
          },
          {
            "name": "jmx",
            "containerPort": 5555,
            "protocol": "TCP"
          }
        ],
        "env": [
          {
            "name": "POD_IP",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "status.podIP"
              }
            }
          },
          {
            "name": "HOST_IP",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "status.hostIP"
              }
            }
          },
          {
            "name": "KAFKA_HEAP_OPTS",
            "value": "-Xms512M -Xmx5000M"
          },
          {
            "name": "KAFKA_ZOOKEEPER_CONNECT",
            "value": "kafka-cp-zookeeper-headless:2181"
          },
          {
            "name": "KAFKA_LOG_DIRS",
            "value": "/opt/kafka/data-0/logs"
          },
          {
            "name": "KAFKA_ADVERTISED_LISTENERS",
            "value": "EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))"
          },
          {
            "name": "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP",
            "value": "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
          },
          {
            "name": "KAFKA_MESSAGE_MAX_BYTES",
            "value": "1.000000012e+09"
          },
          {
            "name": "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR",
            "value": "3"
          },
          {
            "name": "KAFKA_REPLICA_FETCH_MAX_BYTES",
            "value": "1.000000015e+09"
          },
          {
            "name": "KAFKA_SOCKET_REQUEST_MAX_BYTES",
            "value": "2.0048576e+09"
          },
          {
            "name": "KAFKA_JMX_PORT",
            "value": "5555"
          }
        ],
        "resources": {},
        "volumeMounts": [
          {
            "name": "datadir-0",
            "mountPath": "/opt/kafka/data-0"
          },
          {
            "name": "default-token-gwvxx",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent"
      }
    ],
    "restartPolicy": "Always",
    "terminationGracePeriodSeconds": 30,
    "dnsPolicy": "ClusterFirst",
    "serviceAccountName": "default",
    "serviceAccount": "default",
    "nodeName": "worker-1",
    "securityContext": {},
    "hostname": "kafka-cp-kafka-1",
    "subdomain": "kafka-cp-kafka-headless",
    "affinity": {
      "podAntiAffinity": {
        "preferredDuringSchedulingIgnoredDuringExecution": [
          {
            "weight": 1,
            "podAffinityTerm": {
              "labelSelector": {
                "matchExpressions": [
                  {
                    "key": "app",
                    "operator": "In",
                    "values": [
                      "cp-kafka"
                    ]
                  },
                  {
                    "key": "release",
                    "operator": "In",
                    "values": [
                      "kafka"
                    ]
                  }
                ]
              },
              "topologyKey": "kubernetes.io/hostname"
            }
          }
        ]
      }
    },
    "schedulerName": "default-scheduler",
    "tolerations": [
      {
        "key": "node.kubernetes.io/not-ready",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      },
      {
        "key": "node.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      }
    ],
    "priority": 0,
    "enableServiceLinks": true
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-01-29T13:28:22Z"
      },
      {
        "type": "Ready",
        "status": "False",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-01-29T13:31:55Z",
        "reason": "ContainersNotReady",
        "message": "containers with unready status: [cp-kafka-broker]"
      },
      {
        "type": "ContainersReady",
        "status": "False",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-01-29T13:31:55Z",
        "reason": "ContainersNotReady",
        "message": "containers with unready status: [cp-kafka-broker]"
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-01-29T13:28:22Z"
      }
    ],
    "hostIP": "192.168.0.8",
    "podIP": "10.32.16.2",
    "startTime": "2019-01-29T13:28:22Z",
    "containerStatuses": [
      {
        "name": "cp-kafka-broker",
        "state": {
          "waiting": {
            "reason": "CrashLoopBackOff",
            "message": "Back-off 2m40s restarting failed container=cp-kafka-broker pod=kafka-cp-kafka-1_default(bfda1956-23c9-11e9-a615-fa163e9a84ea)"
          }
        },
        "lastState": {
          "terminated": {
            "exitCode": 1,
            "reason": "Error",
            "startedAt": "2019-01-29T13:31:48Z",
            "finishedAt": "2019-01-29T13:31:54Z",
            "containerID": "docker://f9a05b04fc352b53cd2a7ebc5ac2b925a00ddbad7113e21ed3f6d1432934a73d"
          }
        },
        "ready": false,
        "restartCount": 5,
        "image": "confluentinc/cp-kafka:5.0.1",
        "imageID": "docker-pullable://confluentinc/cp-kafka@sha256:c87b1c07fb53b1a82d24b436e53485917876a963dc67311800109fa12fe9a63d",
        "containerID": "docker://f9a05b04fc352b53cd2a7ebc5ac2b925a00ddbad7113e21ed3f6d1432934a73d"
      },
      {
        "name": "prometheus-jmx-exporter",
        "state": {
          "running": {
            "startedAt": "2019-01-29T13:28:23Z"
          }
        },
        "lastState": {},
        "ready": true,
        "restartCount": 0,
        "image": "sha256:36f9e9d8127bdcbea99d3bd9c4cce589d840ddbcc3128f7d23059980490c04e8",
        "imageID": "docker-pullable://solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143",
        "containerID": "docker://fd4d0c31ef2dde396b83b1eb64729878fa7be24c5ff56ebacba16a978133eeac"
      }
    ],
    "qosClass": "BestEffort"
  }
}
```

It looks like the large integer value gets converted to scientific notation at some point which trips up the broker.

**Comment by Tenseiga** [comment]
Use the values in quotes like this  "1000000000000", will fix the issue

**Comment by ankit45621** [comment]
@Tenseiga 

I am using docker-compose in that i am using double quates but still getting same error. Can you please help me for this?

**Comment by Tenseiga** [comment]
@ankit45621

Message.Max.Bytes is int data type. So u may assume max of 2 power 31-1 (int. Max). I assume in this case it's a genuine error. Yes in my ans i did type a lot of 0s. I  randomly types 0s :)

**Comment by ankit45621** [comment]
Is there any way to restric kafka message memory

**Comment by Tenseiga** [comment]
Could you elaborate pls. Whats ur requirement??

**Comment by mmanna-sapfgl** [comment]
> Could you elaborate pls. Whats ur requirement??

The ask here is very simple. The documentation is incorrect and also, if this is being converted to bits or post-processed to increase the value - a clear indication in the documentation should be present.

https://github.com/confluentinc/cp-helm-charts/issues/317

Please could you kindly clarify via this ticket what is the absolute maximum value for an INT/LONG should be for CP ?

Thanks,
