### ISSUE TITLE
Zookeeper Update with Helm Charts

### ISSUE THREAD

**Issue by salvax86** [confluentinc/cp-helm-charts#242]
As administrator, I do not want to go on with an update of my zookeeper cluster, if the new zookeeper node is not running.

If we had the livenessProbe (at least) for zookeeper, the zookeeper quorum is not lost by update. 
Maybe we can make the livenessProbe as optional.

Greetz

**Comment by qshao-pivotal** [comment]
Could you explain more on how livenessprobe prevents the lost of quorum? I didn't get it very clearly.

**Comment by salvax86** [comment]
Sorry for the late reply:
With the poddisruptionbudget (This is present with the helm chart) I say the maximum unavailable pods in statefulset are 1. When updating the pods are updated without waiting for the pods to start successfully. With a ZookeeperEnsemble of 3 you can lose the quorum when the second container is updated. Readiness and AlivenessProbe can help to wait for a successful update. If there are problems with it, the remaining pods will not be touched and the quorum will not be lost.

**Comment by Zefool** [comment]
In other words, the PodDisruptionBudget as is will only test for "has the image been pulled and started", which is insufficient for a working node. 

LivenessProbes would help us register a pod as healthy if and only if it actually is part of the cluster.

**Comment by qshao-pivotal** [comment]
We did have liveness probe and readiness probe before, but removed since don't have enough time to figure out the proper values for those. I got brokers restarted because of failing to pass liveness probe during a performance testing, we decided to remove it for now and added later until we really have a good practical numbers for them. I would recommend a PR with liveness/readiness probe of zookeeper  only first.

**Comment by qshao-pivotal** [comment]
Actually, are you seeing quorum lost in your test? I would love to see the logs. Since a simple liveness and readiness probe won't help with the scenario "quorum lost" scenario unless your liveness/readiness probe does check the status of the "cluster" instead of status of a single pod.

**Comment by salvax86** [comment]
> Since a simple liveness and readiness probe won't help with the scenario "quorum lost" scenario unless your liveness/readiness probe does check the status of the "cluster" instead of status of a single pod.

Honestly, I thought the same thing and my first thought was to use the zookeeper-shell to check the cluster status. 

> Actually, are you seeing quorum lost in your test? I would love to see the logs. 
I start today with a task for stability. I will begin with the actual cp-helmet-chart and attach the logs.

**Comment by salvax86** [comment]
Sorry for late reply.

I write a test with coyote to simulate several edge cases on my microk8s machine. 
First I add the confluent repo and install the helm chart. Then I wait for five minutes in order to wait that all services are well connected. After that I update zookeeper with a new image (at this moment from 5.0.1 to 5.1.2). 

![image](https://user-images.githubusercontent.com/10816934/54364602-7fbd4200-466d-11e9-9305-1ac5e60fee1c.png)

In this instant kubernetes thinks that the confluent-cp-zookeeper-2 is running but it is not. Kubernetes terminates the confluent-cp-zookeeper-1 and the quorum is lost.

Kafka Logs:

```
[2019-03-14 14:34:34,667] INFO [GroupCoordinator 0]: Stabilized group confluent generation 19 (__consumer_offsets-30) (kafka.coordinator.group.GroupCoordinator)
[2019-03-14 14:34:34,671] INFO [GroupCoordinator 0]: Assignment received from leader for group confluent for generation 19 (kafka.coordinator.group.GroupCoordinator)
[2019-03-14 14:35:55,281] INFO Unable to read additional data from server sessionid 0x10001567db60008, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-03-14 14:35:56,886] INFO Opening socket connection to server confluent-cp-zookeeper-headless/10.1.1.183:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-03-14 14:35:56,887] INFO Socket connection established to confluent-cp-zookeeper-headless/10.1.1.183:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-03-14 14:35:56,894] INFO Session establishment complete on server confluent-cp-zookeeper-headless/10.1.1.183:2181, sessionid = 0x10001567db60008, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2019-03-14 14:36:30,738] INFO Unable to read additional data from server sessionid 0x10001567db60008, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-03-14 14:36:32,506] INFO Opening socket connection to server confluent-cp-zookeeper-headless/10.1.1.184:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-03-14 14:36:32,507] INFO Socket connection established to confluent-cp-zookeeper-headless/10.1.1.184:2181, initiating session (org.apache.zookeeper.ClientCnxn)
```

=> No connection to zookeeper 


From zookeeper-0 logs:
```
[2019-03-14 14:35:18,873] WARN Interrupting SendWorker (org.apache.zookeeper.server.quorum.QuorumCnxManager)
[2019-03-14 14:35:18,873] WARN Interrupted while waiting for message on queue (org.apache.zookeeper.server.quorum.QuorumCnxManager)
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
        at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.pollSendQueue(QuorumCnxManager.java:1094)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.access$700(QuorumCnxManager.java:74)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$SendWorker.run(QuorumCnxManager.java:929)
[2019-03-14 14:35:18,874] WARN Send worker leaving thread (org.apache.zookeeper.server.quorum.QuorumCnxManager)
[2019-03-14 14:35:30,359] INFO Received connection request /10.1.1.1:40822 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
[2019-03-14 14:35:30,371] INFO Notification: 1 (message format version), 3 (n.leader), 0x1700000195 (n.zxid), 0x1 (n.round), LOOKING (n.state), 3 (n.sid), 0x17 (n.peerEpoch) FOLLOWING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-03-14 14:35:30,578] INFO Notification: 1 (message format version), 3 (n.leader), 0x1700000195 (n.zxid), 0x1 (n.round), LOOKING (n.state), 3 (n.sid), 0x17 (n.peerEpoch) FOLLOWING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-03-14 14:35:30,987] INFO Notification: 1 (message format version), 3 (n.leader), 0x1700000195 (n.zxid), 0x1 (n.round), LOOKING (n.state), 3 (n.sid), 0x17 (n.peerEpoch) FOLLOWING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-03-14 14:35:31,793] INFO Notification: 1 (message format version), 3 (n.leader), 0x1700000195 (n.zxid), 0x1 (n.round), LOOKING (n.state), 3 (n.sid), 0x17 (n.peerEpoch) FOLLOWING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-03-14 14:35:33,399] INFO Notification: 1 (message format version), 3 (n.leader), 0x1700000195 (n.zxid), 0x1 (n.round), LOOKING (n.state), 3 (n.sid), 0x17 (n.peerEpoch) FOLLOWING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-03-14 14:35:36,602] INFO Notification: 1 (message format version), 3 (n.leader), 0x1700000195 (n.zxid), 0x1 (n.round), LOOKING (n.state), 3 (n.sid), 0x17 (n.peerEpoch) FOLLOWING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-03-14 14:35:43,008] INFO Notification: 1 (message format version), 3 (n.leader), 0x1700000195 (n.zxid), 0x1 (n.round), LOOKING (n.state), 3 (n.sid), 0x17 (n.peerEpoch) FOLLOWING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-03-14 14:35:55,277] WARN Interrupted while waiting for message on queue (org.apache.zookeeper.server.quorum.QuorumCnxManager)
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
        at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.pollSendQueue(QuorumCnxManager.java:1094)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.access$700(QuorumCnxManager.java:74)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$SendWorker.run(QuorumCnxManager.java:929)
[2019-03-14 14:35:55,277] WARN Send worker leaving thread (org.apache.zookeeper.server.quorum.QuorumCnxManager)
[2019-03-14 14:35:55,278] INFO Closed socket connection for client /10.1.1.1:44910 which had sessionid 0x10001567db60007 (org.apache.zookeeper.server.NIOServerCnxn)
[2019-03-14 14:35:55,278] INFO Closed socket connection for client /10.1.1.1:45134 which had sessionid 0x10001567db60008 (org.apache.zookeeper.server.NIOServerCnxn)
[2019-03-14 14:35:55,279] INFO Shutting down (org.apache.zookeeper.server.quorum.FollowerZooKeeperServer)
[2019-03-14 14:35:55,279] INFO shutting down (org.apache.zookeeper.server.ZooKeeperServer)
[2019-03-14 14:35:55,279] INFO Shutting down (org.apache.zookeeper.server.quorum.FollowerRequestProcessor)
[2019-03-14 14:35:55,279] INFO Shutting down (org.apache.zookeeper.server.quorum.CommitProcessor)
[2019-03-14 14:35:55,279] INFO shutdown of request processor complete (org.apache.zookeeper.server.FinalRequestProcessor)
[2019-03-14 14:35:55,279] INFO FollowerRequestProcessor exited loop! (org.apache.zookeeper.server.quorum.FollowerRequestProcessor)
[2019-03-14 14:35:55,279] INFO CommitProcessor exited loop! (org.apache.zookeeper.server.quorum.CommitProcessor)
[2019-03-14 14:35:55,286] INFO Shutting down (org.apache.zookeeper.server.SyncRequestProcessor)
[2019-03-14 14:35:55,287] INFO SyncRequestProcessor exited! (org.apache.zookeeper.server.SyncRequestProcessor)
[2019-03-14 14:35:55,291] INFO LOOKING (org.apache.zookeeper.server.quorum.QuorumPeer)
[2019-03-14 14:35:55,292] INFO New election. My id =  1, proposed zxid=0x1700000195 (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-03-14 14:35:55,294] INFO Notification: 1 (message format version), 1 (n.leader), 0x1700000195 (n.zxid), 0x2 (n.round), LOOKING (n.state), 1 (n.sid), 0x17 (n.peerEpoch) LOOKING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-03-14 14:35:55,294] WARN Cannot open channel to 2 at election address confluent-cp-zookeeper-1.confluent-cp-zookeeper-headless.fronting/10.1.1.180:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:558)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:534)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:454)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:435)
        at java.lang.Thread.run(Thread.java:748)
[2019-03-14 14:35:55,327] WARN Failed to resolve address: confluent-cp-zookeeper-1.confluent-cp-zookeeper-headless.fronting (org.apache.zookeeper.server.quorum.QuorumPeer)
java.net.UnknownHostException: confluent-cp-zookeeper-1.confluent-cp-zookeeper-headless.fronting: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:180)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:591)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:534)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:454)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:435)
        at java.lang.Thread.run(Thread.java:748)
[2019-03-14 14:35:55,336] INFO Notification: 1 (message format version), 3 (n.leader), 0x1700000195 (n.zxid), 0x2 (n.round), LOOKING (n.state), 3 (n.sid), 0x17 (n.peerEpoch) LOOKING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
```

At that point the quorum is lost.

> unless your liveness/readiness probe does check the status of the "cluster" instead of status of a single pod.

I think the same way. The activity / readiness test should check the cluster status.

The issue, however, is the long initialization time of confluent images. 
Checking the status of a single pod already prevents Kubernetes from updating other pods, if the first updated pod does not accept connections to the client port.

**Comment by Dimpison** [comment]
are there any updates on this?

**Comment by cloudbow** [comment]
In k8s with eks I have the same problem with m4.xlarge machine . What I did is increase zookeeper memory and increase tickTime . 

  cp-helm-charts:
    cp-kafka-rest:
      enabled: false
    cp-ksql-server:
      enabled: false
    cp-zookeeper:
      heapOptions: "-Xms1024M -Xmx1024M"
      tickTime: 10000
