### ISSUE TITLE
Strange 404 error in log for kafka-connect when using Kafka Connect chart

### ISSUE THREAD

**Issue by MaxWinther** [confluentinc/cp-helm-charts#290]
Hi,

I get an strange 404 error, apparently from with Kafka Connect itself

[2019-05-16 10:33:52,392] INFO 10.20.40.91 - - [16/May/2019:10:33:52 +0000] "GET /health HTTP/1.1" 404 49  2 (org.apache.kafka.connect.runtime.rest.RestServer)
[2019-05-16 10:33:52,393] ERROR Uncaught exception in REST call to /health (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper)
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:274)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)

regards

**Comment by MaxWinther** [comment]
Sorry, it turned out to be an LoadBalancers polling the kafka-connect component
