### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space on Kafka Connect even increasing the Xmx config

### ISSUE THREAD

**Issue by codependent** [confluentinc/cp-helm-charts#312]
I'm trying to install Kafka Connect on Kubernetes using the provided chart but keep getting an OutOfMemoryError event though I've modified the heap config up to 8GB. I haven't modified the initial installation, no additional connector plugins, etc.

I've tried with the master branch (5.3.0) and the v5.2.2-1 tag.

Installation command: `helm install --set kafka.bootstrapServers="xxx.confluent.cloud:9092" cp-kafka-connect --namespace kafka`

Startup log:

```
...
HOSTNAME=warped-waterbuffalo-cp-kafka-connect-589c5cd4bc-7lm2j
KAFKA_ADVERTISED_LISTENERS=
KAFKA_HEAP_OPTS=-Xms512M -Xmx8g
KAFKA_JMX_PORT=5555
KAFKA_VERSION=2.2.1cp1
KAFKA_ZOOKEEPER_CONNECT=
...
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka version: 2.2.1-cp1
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka commitId: 7356dae0d4d91aa2
[kafka-admin-client-thread | adminclient-1] ERROR org.apache.kafka.common.utils.KafkaThread - Uncaught exception in thread 'kafka-admin-client-thread | adminclient-1':
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:112)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:424)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:385)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:651)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:572)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:483)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:535)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1131)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by codependent** [comment]
It was a memory limitation in my K8s cluster, I'm closing the issue then.

**Comment by gAmUssA** [comment]
@codependent thanks for the update!

**Comment by sgraham785** [comment]
@codependent care to elaborate on your fix? 
I am facing the same issue with heap set to  "-Xmx1G -Xms1G"

**Comment by codependent** [comment]
@sgraham785 My problem was the worker nodes of my k8s cluster had 2GB of RAM so when a Kafka Connect pod was starting it obviously threw the OutOfMemoryError since it was requesting up to 8GB.

I'd suggest you increase the heap size, only 1GB seems to low.

**Comment by gerbrand** [comment]
For other people who are searching the web for solution to outofmemory issues, I'd recommend to give Kafka Connect quite a lot of memory during creation of initial snapshot. That takes up a lot of memory, especially if you have large databases/tables. After a snapshot Debezium Connect starts reading the binlog which doesn't use of memory. Currently using the setting -Xmx12Gg:
`KAFKA_HEAP_OPTS=-Xms256M -Xmx12G `
better safe than sorry
