### ISSUE TITLE
Headless zookeeper service not reachable

### ISSUE THREAD

**Issue by gohanbg** [confluentinc/cp-helm-charts#316]
I'm trying to deploy the confluent platform on Rancher's **k3s** server. It all looks good, but when I go to the logs of any zookeeper instance I see the following:

>    kubectl logs -f cc-cp-zookeeper-0 cp-zookeeper-server 
===> ENV Variables ...
ALLOW_UNSIGNED=false
CC_CP_ZOOKEEPER_PORT=tcp://10.43.16.45:2181
CC_CP_ZOOKEEPER_PORT_2181_TCP=tcp://10.43.16.45:2181
CC_CP_ZOOKEEPER_PORT_2181_TCP_ADDR=10.43.16.45
CC_CP_ZOOKEEPER_PORT_2181_TCP_PORT=2181
CC_CP_ZOOKEEPER_PORT_2181_TCP_PROTO=tcp
CC_CP_ZOOKEEPER_SERVICE_HOST=10.43.16.45
CC_CP_ZOOKEEPER_SERVICE_PORT=2181
CC_CP_ZOOKEEPER_SERVICE_PORT_CLIENT=2181
COMPONENT=zookeeper
CONFLUENT_DEB_VERSION=1
CONFLUENT_MAJOR_VERSION=5
CONFLUENT_MINOR_VERSION=3
CONFLUENT_MVN_LABEL=
CONFLUENT_PATCH_VERSION=0
CONFLUENT_PLATFORM_LABEL=
CONFLUENT_VERSION=5.3.0
CUB_CLASSPATH=/etc/confluent/docker/docker-utils.jar
HOME=/root
HOSTNAME=cc-cp-zookeeper-0
KAFKA_HEAP_OPTS=-Xms1024M -Xmx1024M
KAFKA_JMX_PORT=5555
KAFKA_VERSION=5.3.0
KUBERNETES_PORT=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_HOST=10.43.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
LANG=C.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
PYTHON_PIP_VERSION=8.1.2
PYTHON_VERSION=2.7.9-1
SCALA_VERSION=2.12
SHLVL=2
ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL=24
ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT=3
ZOOKEEPER_CLIENT_PORT=2181
ZOOKEEPER_INIT_LIMIT=10
ZOOKEEPER_MAX_CLIENT_CNXNS=60
ZOOKEEPER_SERVERS=0.0.0.0:2888:3888;cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging:2888:3888;cc-cp-zookeeper-2.cc-cp-zookeeper-headless.messaging:2888:3888
ZOOKEEPER_SERVER_ID=1
ZOOKEEPER_SYNC_LIMIT=5
ZOOKEEPER_TICK_TIME=10000
ZULU_OPENJDK_VERSION=8=8.38.0.13
_=/usr/bin/env
===> User
uid=0(root) gid=0(root) groups=0(root)
===> Configuring ...
===> Running preflight checks ... 
===> Check if /var/lib/zookeeper/data is writable ...
===> Check if /var/lib/zookeeper/log is writable ...
===> Launching ... 
===> Printing /var/lib/zookeeper/data/myid 
1===> Launching zookeeper ... 
[2019-08-29 11:03:48,264] INFO Reading configuration from: /etc/kafka/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2019-08-29 11:04:08,330] WARN Failed to resolve address: cc-cp-zookeeper-2.cc-cp-zookeeper-headless.messaging (org.apache.zookeeper.server.quorum.QuorumPeer)
java.net.UnknownHostException: cc-cp-zookeeper-2.cc-cp-zookeeper-headless.messaging: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:181)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.<init>(QuorumPeer.java:153)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:240)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:152)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:104)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:81)
[2019-08-29 11:04:28,362] WARN Failed to resolve address: cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging (org.apache.zookeeper.server.quorum.QuorumPeer)
java.net.UnknownHostException: cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:181)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.<init>(QuorumPeer.java:153)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:240)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:152)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:104)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:81)
[2019-08-29 11:04:28,376] INFO Resolved hostname: 0.0.0.0 to address: /0.0.0.0 (org.apache.zookeeper.server.quorum.QuorumPeer)
[2019-08-29 11:04:28,379] INFO Defaulting to majority quorums (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2019-08-29 11:04:28,403] INFO autopurge.snapRetainCount set to 3 (org.apache.zookeeper.server.DatadirCleanupManager)
[2019-08-29 11:04:28,404] INFO autopurge.purgeInterval set to 24 (org.apache.zookeeper.server.DatadirCleanupManager)
[2019-08-29 11:04:28,411] INFO Purge task started. (org.apache.zookeeper.server.DatadirCleanupManager)
[2019-08-29 11:04:28,431] INFO Starting quorum peer (org.apache.zookeeper.server.quorum.QuorumPeerMain)
[2019-08-29 11:04:28,440] INFO Purge task completed. (org.apache.zookeeper.server.DatadirCleanupManager)
[2019-08-29 11:04:28,452] INFO Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory (org.apache.zookeeper.server.ServerCnxnFactory)
[2019-08-29 11:04:28,454] INFO binding to port 0.0.0.0/0.0.0.0:2181 (org.apache.zookeeper.server.NIOServerCnxnFactory)
[2019-08-29 11:04:28,456] INFO tickTime set to 10000 (org.apache.zookeeper.server.quorum.QuorumPeer)
[2019-08-29 11:04:28,459] INFO initLimit set to 10 (org.apache.zookeeper.server.quorum.QuorumPeer)
[2019-08-29 11:04:28,460] INFO minSessionTimeout set to -1 (org.apache.zookeeper.server.quorum.QuorumPeer)
[2019-08-29 11:04:28,460] INFO maxSessionTimeout set to -1 (org.apache.zookeeper.server.quorum.QuorumPeer)
[2019-08-29 11:04:28,476] INFO QuorumPeer communication is not secured! (org.apache.zookeeper.server.quorum.QuorumPeer)
[2019-08-29 11:04:28,477] INFO quorum.cnxn.threads.size set to 20 (org.apache.zookeeper.server.quorum.QuorumPeer)
[2019-08-29 11:04:28,493] INFO My election bind port: /0.0.0.0:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
[2019-08-29 11:04:28,502] INFO LOOKING (org.apache.zookeeper.server.quorum.QuorumPeer)
[2019-08-29 11:04:28,509] INFO New election. My id =  1, proposed zxid=0x0 (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-08-29 11:04:28,510] INFO Notification: 1 (message format version), 1 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 1 (n.sid), 0x0 (n.peerEpoch) LOOKING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
[2019-08-29 11:04:28,512] WARN Cannot open channel to 2 at election address cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
java.net.UnknownHostException: cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:558)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:534)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:454)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:435)
	at java.lang.Thread.run(Thread.java:748)
[2019-08-29 11:04:28,519] WARN Failed to resolve address: cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging (org.apache.zookeeper.server.quorum.QuorumPeer)
java.net.UnknownHostException: cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:181)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:591)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:534)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:454)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:435)
	at java.lang.Thread.run(Thread.java:748)
[2019-08-29 11:04:28,521] WARN Cannot open channel to 3 at election address cc-cp-zookeeper-2.cc-cp-zookeeper-headless.messaging:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
java.net.UnknownHostException: cc-cp-zookeeper-2.cc-cp-zookeeper-headless.messaging
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:558)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:534)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:454)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:435)
	at java.lang.Thread.run(Thread.java:748)
[2019-08-29 11:04:48,539] WARN Failed to resolve address: cc-cp-zookeeper-2.cc-cp-zookeeper-headless.messaging (org.apache.zookeeper.server.quorum.QuorumPeer)
java.net.UnknownHostException: cc-cp-zookeeper-2.cc-cp-zookeeper-headless.messaging: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:181)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:591)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:534)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:454)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:435)
	at java.lang.Thread.run(Thread.java:748)
[2019-08-29 11:04:48,545] WARN Cannot open channel to 2 at election address cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
java.net.UnknownHostException: cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:558)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:610)
	at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:838)
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:958)
[2019-08-29 11:05:08,558] WARN Failed to resolve address: cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging (org.apache.zookeeper.server.quorum.QuorumPeer)
java.net.UnknownHostException: cc-cp-zookeeper-1.cc-cp-zookeeper-headless.messaging: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:181)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:591)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:610)
	at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:838)
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:958)
[2019-08-29 11:05:08,561] WARN Cannot open channel to 3 at election address cc-cp-zookeeper-2.cc-cp-zookeeper-headless.messaging:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
java.net.UnknownHostException: cc-cp-zookeeper-2.cc-cp-zookeeper-headless.messaging
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:558)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:610)
	at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:838)
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:958)

When I try to get information about the state of the deployment I see:

>    kga
NAME                    READY   STATUS    RESTARTS   AGE
pod/cc-cp-zookeeper-0   2/2     Running   0          6m16s
pod/cc-cp-zookeeper-1   2/2     Running   0          6m14s
pod/cc-cp-zookeeper-2   2/2     Running   0          6m12s
NAME                               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
service/cc-cp-zookeeper            ClusterIP   10.43.16.45   <none>        2181/TCP            6m16s
service/cc-cp-zookeeper-headless   ClusterIP   None          <none>        2888/TCP,3888/TCP   6m16s
NAME                               READY   AGE
statefulset.apps/cc-cp-zookeeper   3/3     6m16s

I can provide more info if needed.

**Comment by gohanbg** [comment]
It is a problem with k3s, rather than zookeeper. Closing the issue
