### ISSUE TITLE
Inconsistent Documentation/Limit for message.max.bytes and replia.fetch.max.bytes

### ISSUE THREAD

**Issue by mmanna-sapfgl** [confluentinc/cp-helm-charts#317]
This is somewhat related to issue mentioned here
https://github.com/confluentinc/cp-helm-charts/issues/235

We have reproduced this by deploying the helm chart to GCP with the following settings in Values.YAML

```
log.retention.hours=1
log.cleanup.policy=delete
message.max.bytes=21971520
replica.fetch.max.bytes= 21971520
num.partitions=5
default.replication.factor=5
```

The broker startup failed with the following exceptions:

```
[2019-08-29 16:50:52,253] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2019-08-29 16:50:52,816] ERROR Fatal error during SupportedServerStartable startup. Prepare to shutdown (io.confluent.support.metrics.SupportedKafka)
org.apache.kafka.common.config.ConfigException: Invalid value 2.197152e+07 for configuration message.max.bytes: Not a number of type INT
    at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:718)
    at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:473)
    at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:466)
    at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
    at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
    at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1111)
    at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
    at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
    at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1091)
    at kafka.server.KafkaConfig.fromProps(KafkaConfig.scala)
    at io.confluent.support.metrics.SupportedServerStartable.<init>(SupportedServerStartable.java:52)
    at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:45)
```

The ask here is very simple (as Apache Kafka 2.3.0 from github doesn't have this issue):

1) The documentation on confluent platform doesn't mention anywhere that there is a limit on these. Integer.MAX_VALUE should be honoured. And if not, confluent documentation must clearly state why.

https://docs.confluent.io/current/installation/configuration/broker-configs.html

2) Please consider this a priority for bugfix release or update to Helm Chart.

**Comment by mmanna-sapfgl** [comment]
We have identified the issue. It appears that if you input a number without quoting (double quotes), this is magically converted into some number which fails parsing. We used helm chart version 0.16.2.

Once the number is surrounded using double-quotes, it's working the same as standalone binary on Windows/Linux.

**Comment by mmanna-sapfgl** [comment]
closing this as per previous comments.
