### ISSUE TITLE
Error on new install related to headless service

### ISSUE THREAD

**Issue by PPACI** [confluentinc/cp-helm-charts#367]
Hi cp-helm-template.

I'm currently trying to deploy the **master** branch of this repository.
I've used a raw, empty, new minikube cluster to avoid side effect.

While helm (3.0) if successfully creating the release, some of the containers are not booting properly.

For example, the pods `cp-confluent-cp-kafka-0` is crashing at boot with 

```text
│ cp-kafka-broker java.io.IOException: Client was shutdown before response was read                                                                                                                            │
│ cp-kafka-broker     at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:109)                                                                                               │
│ cp-kafka-broker     at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:257)                                                                                                         │
│ cp-kafka-broker     at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)                                                                                                                       │
│ cp-kafka-broker [2020-01-16 12:38:32,396] ERROR [RequestSendThread controllerId=0] Controller 0 fails to send a request to broker cp-confluent-cp-kafka-1.cp-confluent-cp-kafka-headless.cp-confluent:9092 ( │
│ id: 1 rack: null) (kafka.controller.RequestSendThread)                                                                                                                                                       │
│ cp-kafka-broker java.lang.InterruptedException                                                                                                                                                               │
│ cp-kafka-broker     at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)                                                                     │
│ cp-kafka-broker     at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)                                                                                                                    │
│ cp-kafka-broker     at kafka.utils.ShutdownableThread.pause(ShutdownableThread.scala:82)                                                                                                                     │
│ cp-kafka-broker     at kafka.controller.RequestSendThread.backoff$1(ControllerChannelManager.scala:238)                                                                                                      │
│ cp-kafka-broker     at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:266)                                                                                                         │
│ cp-kafka-broker     at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)  
```

I've seen other errors related to this headless service in other pods too, such as

```text
│ cp-ksql-server [main] WARN org.apache.kafka.clients.ClientUtils - Couldn't resolve server PLAINTEXT://cp-confluent-cp-kafka-headless:9092 from bootstrap.servers as DNS resolution failed for cp-confluent-c │

```
I've tried a dumb patch where I've transformed the stateless service into a cluster IP, but the broker are still not being to be requested.

Do you have any idea of what to investigate ?

**Comment by jcsky** [comment]
Hi @PPACI ,
I have the same issue, how did you resolve it?

**Comment by PPACI** [comment]
I don’t remember right know. I’ll check 👍

**Comment by shakilkumarr** [comment]
Did you find the solution. I am facing the same

**Comment by PPACI** [comment]
Yes today I have a working setup.
I remember that I had issue with linkerd.
I had some namespace annotated for auto injection. 
But I’m not 100% sure it was the solution.
