### ISSUE TITLE
ERROR io.confluent.admin.utils.ClusterStatus - Timed out waiting for connection to Zookeeper server [zookeeper.operator.svc.cluster.local:2181/kafka-operator].

### ISSUE THREAD

**Issue by tamipangadil** [confluentinc/cp-helm-charts#395]
I'm trying to install Confluent Operator in our K8s cluster with Istio in it. Although the instruction wasn't included in their quick start guidelines, I'm hoping someone maybe came across with this problem.

Here's the steps I've done:
1. Install the cluster with minimum requirements of 10 nodes
2. Install `istio` components
2. Install the `operator` charts
3. Install `zookeeper` charts
4. Install `kafka` charts <--- **Always failed**

Errors based on kafka container:
```
[main-SendThread(zookeeper.operator.svc.cluster.local:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper.operator.svc.cluster.local/46.19.XXX.XXX:2181. Will not attempt to authenticate using SASL (unknown error)
[main-SendThread(zookeeper.operator.svc.cluster.local:2181)] INFO org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /192.168.XX.XX:45356, server: zookeeper.operator.svc.cluster.local/46.19.XXX.XXX:2181
[main-SendThread(zookeeper.operator.svc.cluster.local:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server zookeeper.operator.svc.cluster.local/46.19.XXX.XXX:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)

[main] ERROR io.confluent.admin.utils.ClusterStatus - Timed out waiting for connection to Zookeeper server [zookeeper.operator.svc.cluster.local:2181/kafka-operator].
[main-SendThread(zookeeper.operator.svc.cluster.local:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper.operator.svc.cluster.local/46.19.XXX.XXX:2181. Will not attempt to authenticate using SASL (unknown error)
[main-SendThread(zookeeper.operator.svc.cluster.local:2181)] INFO org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /192.168.XX.XX:41440, server: zookeeper.operator.svc.cluster.local/46.19.XXX.XXX:2181
[main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x0 closed
[main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x0
```

Tried some workaround with no luck.
1. Install VirtualService to explicitly point to the `zookeeper` service
```
cat <<EOF | kubectl -n operator apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zookeeper
spec:
  hosts:
  - zookeeper.operator.svc.cluster.local
  http:
  - name: zookeeper
    route:
    - destination:
        host: zookeeper
---
EOF
``` 

2. And also ServiceEntry for both `zookeeper` and `kafka`
```
cat <<EOF | kubectl -n operator apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: zookeeper
spec:
  location: MESH_INTERNAL
  hosts:
  - zookeeper.operator.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
EOF


cat <<EOF | kubectl -n operator apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kafka
spec:
  location: MESH_INTERNAL
  hosts:
  - kafka.operator.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
EOF
```

Is it related to any configuration of Confluent helm charts?

Thanks!

Reference page: [Confluent Operator Quick Start](https://docs.confluent.io/current/installation/operator/co-quickstart.html).

**Comment by suraj2410** [comment]
getting the same issue. were you able to solve this?

**Comment by sanvir10** [comment]
Exist update about this??, just today i start with problems with kafka.
```
ERROR io.confluent.admin.utils.ClusterStatus - Timed out waiting for connection to Zookeeper server
```

I have 3 replicas from Zookeeper and Kafka but kafka-0 is off, on logs i see the error.

**Comment by terryf82** [comment]
Seeing this more and more in our clusters now too, increasing CPU / memory for the zookeeper pods doesn't seem to help.

**Comment by sanvir10** [comment]
Yes, this is not a resource problem, i tested remove istio:

```
kubectl label namespace NAMESPACE istio-injection-
```

and reinstall kafka and this is working now, i think in the cluster exist components that block the communication, but i'm not sure.

**Comment by terryf82** [comment]
Based on this discussion and a similar [thread](https://confluentcommunity.slack.com/archives/C49R61XMM/p1602230071141800) in the Confluent #ops Slack, I believe it is a [bug](https://issues.apache.org/jira/browse/ZOOKEEPER-3828) in the version of Zookeeper that Confluent is using (`3.5.8`) that is responsible.

We have successfully tested disabling _cp-zookeeper_ in these charts, and running Apache Zookeeper `3.6.2` via the [incubator helm charts](https://github.com/helm/charts/tree/master/incubator/zookeeper) as part of a confluent-apache hybrid cluster. So far we've had nearly a week of stable running, even after several routine zookeeper pod restarts.

**Comment by nrvmodi** [comment]
I am facing the same issue, but it happened after few days (1 day). Not the time of deployment.

**Comment by bainilybi** [comment]
I have the save issue. The error log like this:

java.nio.channels.UnresolvedAddressException                                                                                                                                                  │
│     at sun.nio.ch.Net.checkAddress(Net.java:101)                                                                                                                                              │
│     at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)                                                                                                                       │
│     at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)                                                                                              │
│     at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)                                                                                                         │
│     at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)                                                                                                          │
│     at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)                                                                                                                   │
│ [main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper:2181. Will not attempt to authenticate using SASL (unknown error)      │
│ [main-SendThread(zookeeper:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server zookeeper:2181, unexpected error, closing socket connection and attempting reconnect          │
│ java.nio.channels.UnresolvedAddressException                                                                                                                                                  │
│     at sun.nio.ch.Net.checkAddress(Net.java:101)                                                                                                                                              │
│     at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)                                                                                                                       │
│     at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)                                                                                              │
│     at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)                                                                                                         │
│     at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)                                                                                                          │
│     at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)                                                                                                                   │
│ [main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper:2181. Will not attempt to authenticate using SASL (unknown error)      │
│ [main-SendThread(zookeeper:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server zookeeper:2181, unexpected error, closing socket connection and attempting reconnect          │
│ java.nio.channels.UnresolvedAddressException                                                                                                                                                  │
│     at sun.nio.ch.Net.checkAddress(Net.java:101)                                                                                                                                              │
│     at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)                                                                                                                       │
│     at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)                                                                                              │
│     at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)                                                                                                         │
│     at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)                                                                                                          │
│     at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)                                                                                                                   │
│ [main] ERROR io.confluent.admin.utils.ClusterStatus - Timed out waiting for connection to Zookeeper server [zookeeper:2181].                                                                  │
│ [main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper:2181. Will not attempt to authenticate using SASL (unknown error)      │
│ [main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x0 closed                                                                                                                              │
│ [main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x0                                                                                              │
│ stream closed

**Comment by matt-best-elateral** [comment]
I have the same problem.  It appears that when the zookeeper leader restarts, one of the followers successfully is promoted to leader, but the cp-kafka brokers are unable to connect to the new leader.  I edited the zookeeper statefulset, changing the number of replicas from `3` to `0`, and then after saving and waiting for all of the zookeeper instances to close change the number of replicas back up to `3`.  Once the zookeeper instances were running again, the brokers were once again able to connect to zookeeper and resume running.  Editing the number of zookeeper replicas like this obviously isn't a fix to the problem.
