### ISSUE TITLE
ksql-server pods crashing

### ISSUE THREAD

**Issue by Rishikeshpal** [confluentinc/cp-helm-charts#528]
ksqldb-server pods are getting terminated, pods throw the below errors:
[2021-04-27 09:04:54,852] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:66)
java.lang.RuntimeException: Failed to get Kafka cluster information
	at io.confluent.ksql.services.KafkaClusterUtil.getKafkaClusterId(KafkaClusterUtil.java:107)
	at io.confluent.ksql.rest.server.StandaloneExecutorFactory.create(StandaloneExecutorFactory.java:64)
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:147)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:59)
Caused by: java.util.concurrent.TimeoutException
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
	at io.confluent.ksql.services.KafkaClusterUtil.getKafkaClusterId(KafkaClusterUtil.java:105)

Any help will be appreciated?

**Comment by gAmUssA** [comment]
How did you install it?

**Comment by Rishikeshpal** [comment]
I used the helm install.
