### ISSUE TITLE
Helm chart deployment is failing when my cluster-domain is not cluster.local

### ISSUE THREAD

**Issue by mikeoleary** [confluentinc/cp-helm-charts#634]
I have used helm to install Confluent for Kubernetes, starting with the [quickstart guide](https://docs.confluent.io/operator/current/co-quickstart.html#co-long-quickstart).

However, my cluster's DNS domain is _not_ **cluster.local**. In my case it's a custom and compliant value that is in the format xxx.yyy.tenant.local

When I follow the steps to deploy via helm, my first Zookeeper pod in my StatefulSet constantly throws this error:

````
[ERROR] 2023-02-13 18:42:16,502 [ListenerHandler-zookeeper-0.zookeeper.confluent.svc.cluster.local:3888] org.apache.zookeeper.server.quorum.QuorumCnxManager acceptConnections - Exception while listening
java.net.SocketException: Unresolved address
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:393)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:354)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.createNewServerSocket(QuorumCnxManager.java:1135)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.acceptConnections(QuorumCnxManager.java:1064)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.run(QuorumCnxManager.java:1033)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
````

Note, there is no service with a DNS name of "**zookeeper.confluent.svc.cluster.local**" which you can see is attempted in the logs. There is a service with DNS name of "zookeeper.confluent.svc.xxx.yyy.tenant.local" but that is not what is being accessed by this container.

How can I deploy Confluent for Kubernetes on a cluster with a custom cluster domain?

**Comment by MYuitsu** [comment]
@mikeoleary You can use 
```yaml
spec:
  k8sClusterDomain: "xxx.yyy.tenant.local"
```
You can find more config in [https://docs.confluent.io/operator/current/co-api.html#tag/Zookeeper](https://docs.confluent.io/operator/current/co-api.html#tag/Zookeeper)
